# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'YTApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for Wick
  
  
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  rn_path = '../node_modules/react-native'
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'DevSupport',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'Google-Mobile-Ads-SDK'
end


